### ISSUE TITLE
CSS and JavaScript errors

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/NeatlineWaypoints#6]
In Omeka 2.5.1 (with Waypoints 2.0.2), the 

`/plugins/NeatlineWaypoints/views/shared/css/dist/waypoints-public.css`
`/plugins/NeatlineWaypoints/views/shared/css/dist/waypoints-public.js`

Are throwing an `net::ERR_ABORTED` error. In the request dump (see below), it looks like the `'Action "neatlinewaypoints" does not exist...'`. 

When you attempt to directly access the resource (e.g. http://new.breadnutislandpen.net/plugins/NeatlineWaypoints/views/shared/css/dist/waypoints-public.css) Omeka throws an error. 

Any ideas on what might be going on here?

=========

```
Request URI: /plugins/NeatlineWaypoints/views/shared/css/dist/waypoints-public.css
Params:
Array
(
    [controller] => plugins
    [action] => NeatlineWaypoints
    [views] => shared
    [css] => dist
    [module] => default
    [exception] => exception 'Zend_Controller_Action_Exception' with message 'Action "neatlinewaypoints" does not exist and was not trapped in __call()' in /home/breadnut/omeka-2.5.1/application/libraries/Zend/Controller/Action.php:485
Stack trace:
#0 /home/breadnut/omeka-2.5.1/application/libraries/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('neatlinewaypoin...', Array)
#1 /home/breadnut/omeka-2.5.1/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('neatlinewaypoin...')
#2 /home/breadnut/omeka-2.5.1/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /home/breadnut/omeka-2.5.1/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#4 /home/breadnut/omeka-2.5.1/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/breadnut/omeka-2.5.1/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#6 /home/breadnut/omeka-2.5.1/index.php(23): Omeka_Application->run()
#7 {main}
    [exception_type] => EXCEPTION_NO_ACTION
)
```

**Comment by waynegraham** [comment]
Forgot to add, this is with Neatline 2.5.1 that were from an upgrade.

- Omeka 2.2.2 -> 2.5.1
- Neatline 2.3.0 -> 2.6.1
- Neatline Waypoints 2.0.2 -> 2.0.2

Other plugins enabled:

- Neatline Simile (not used)
- Simple Pages (not used)

**Comment by zerocrates** [comment]
FYI this type of error almost always just means the file is not actually there.
